### PR TITLE
adding numba based add function

### PR DESCRIPTION
**Pull request by ericgyounkin**
trying to improve on vgrid.add using numba JIT.  Applying parallelism and nopython seems to increase performance by up to 340%.  numba does not like to compile functions/classes (except for numba compiled functions with the decorator) so applying this method within the main class is impossible.  Might want to think about restructuring the project if this is too messy and we want to proceed in this direction.

### CODE REVIEW

**Comment by valschmidt** [comment]
I'm testing this in a jupiter notebook cell with the following and get numba errors I don't understand. 

```
import vgrid
import numpy as np

xx = np.random.random((10000,1))*100.0 
yy = np.random.random((10000,1))*100.0  
zz = np.exp( np.sqrt(((xx-50.)**2 + (yy-50.)**2))/50.0)

def dovgrid(xx,yy,zz,r):  
    G = vgrid.vgrid(cs=1,cinf=1.0)  
    #G.add(xx,yy,zz,1) 
    G.numba_add(xx,yy,zz,1)
    return G.zz()

%timeit vg_z = dovgrid(xx,yy,zz,1.0)
```

There's more to the error message but this seems to capture the heart of it:

```
In definition 12:
    TypeError: cannot index array(int64, 0d, C) with 1 indices: [array(int64, 1d, C)]
    raised from /anaconda3/lib/python3.7/site-packages/numba/typing/arraydecl.py:87
In definition 13:
    TypeError: cannot index array(int64, 0d, C) with 1 indices: [array(int64, 1d, C)]
    raised from /anaconda3/lib/python3.7/site-packages/numba/typing/arraydecl.py:87
```

...which seems to indicate that there's an attempt to index into a zero dimensional array.

Does this work for you?

**Comment by ericgyounkin** [comment]
Ah that was my mistake.  I missed one place where it assumed you were using a weight vector instead of just a number.  I fixed that part of the code in the recent commit.  My tests were with a w that was the same shape as your xx.

One thing you'll find is that your method is going to be faster for 10000 points, as (I think) the overhead in the just in time compiler working on these functions will be greater than the benefit of numba.  It seems like you need maybe 100,000 points or more to benefit.  Which encompasses most situations where you are using real data.

There is a way to cache the JIT function so that it doesn't have to do the nopython compilation on run, but I couldn't get it to work.  It would just hang on run.  It's probably worth looking at further, if we go down this road.  Maybe we should discuss future plans for this stuff at some point.

**Comment by valschmidt** [comment]
I pulled your changes, but oddly they didn't fix the problem for me. I get the same error for the case when w.size !=1, even though w.size = 1. I admit I don't have a good sense of how numba works yet and I have difficulty understanding the errors raised and how to fix them. I'm not sure I understand how to help numba understand that a field may be scalar or vector and allow for either case. One solution is that we force the value to be a vector (if a scalar is specified, internally we make it a vector). 

BTW, I tested this numba implementation passing w as a vector of size xx.shape = (10000,1) , just to see it run. It completed 14 times faster than my implementation!  I should probably do some more testing to see how reproducible it is, but very promising.

**Comment by ericgyounkin** [comment]
Hmm, that is weird.  I modified it to make weight a vector.  

Did you do your numba_add test with timeit?  It would probably show a huge improvement with many iterations.  On the first run (or if you ran it once) for input of that size, I would think it would be slower or as fast as your original implementation.

**Comment by valschmidt** [comment]
Merged!

**Pull request closed without merging**
